---
- hosts: localhost
  remote_user: root

  tasks:

    - name: create log dirs or fail trying
      command: bash /opt/pdx_res/ansible/create_logs.sh
      tags: ['shell', 'logs']

    - name: install latest pip in virtualenv
      pip:
        name: pip
        state: latest
        virtualenv: '/opt/pdx_res/current/venv'
        extra_args: '--log /var/log/pip.log'
      tags: ['pip', 'install']

    - name: install requirements
      pip:
        requirements: /opt/pdx_res/current/pdx_res/requirements.txt
        virtualenv: /opt/pdx_res/current/venv/
      tags: ['requirements', 'install', 'pip']

    - name: install packages based on package.json.
      npm:
        path: /opt/pdx_res/current/gulper
      tags: ['node', 'npm', 'gulp']

    - name: install gulp
      npm:
        name: gulp
        path: /opt/pdx_res/current/gulper
      tags: ['node', 'npm', 'gulp']

    - name: Run gulp
      command: /opt/pdx_res/current/gulper/node_modules/gulp/bin/gulp.js
      args:
        chdir: /opt/pdx_res/current/gulper
      tags: ['npm', 'gulp', 'assets']