---
- hosts: localhost
  remote_user: root

  tasks:

    - name: create log dirs or fail trying
      command: bash /opt/pdx_res/ansible/create_logs.sh
      tags: ['shell', 'logs']

    - name: install latest pip in virtualenv
      pip:
        name: pip
        state: latest
        virtualenv: '/opt/pdx_res/current/venv'
        extra_args: '--log /var/log/pip.log'
      tags: ['pip', 'install']

    - name: install requirements
      pip:
        requirements: /opt/pdx_res/current/requirements.txt
        virtualenv: /opt/pdx_res/current/venv/
      tags: ['requirements', 'install', 'pip']

  #   - name: update uwsgi configs
  #     file:
  #       src: '/opt/pdx_res/current/configs/site_uwsgi.ini'
  #       dest: '/etc/uwsgi/vassals'
  #       state: link
  #       force: yes
  #     notify: restart nginx
  #     ignore_errors: yes
  #     tags: ['uwsgi', 'server']

  #   - name: update nginx configs
  #     file:
  #       src: '/opt/pdx_res/current/configs/site_nginx.conf'
  #       dest: '/etc/nginx/conf.d'
  #       state: link
  #       force: yes
  #     notify: restart nginx
  #     tags: ['nginx', 'server']

  # handlers:
  # - name: restart nginx
  #   command: service nginx restart